version: '3.8'

services:
  api:
    build:
      context: .           
      dockerfile: Dockerfile
    container_name: packing-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    command: npm run start:dev  
